name: AzureSpringCloud
on: push
env:
  ASC_PACKAGE_PATH: ${{ github.workspace }}
  key: ${{ secrets.AZURE_SUBSCRIPTION_KEY }}
  AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION_KEY }}
  
jobs:
  deploy_to_production:
    runs-on: ubuntu-latest
    name: deploy to production with source code
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v2

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: deploy to production step with soruce code
        uses: azure/spring-cloud-deploy@v1
        with:
          azure-subscription: ${{ env.AZURE_SUBSCRIPTION }}
          action: deploy
          service-name: dualtranslate
          app-name: translator
          use-staging-deployment: false
          package: ${{ env.ASC_PACKAGE_PATH }}